

CREATE TABLE account (
                         id bigint NOT NULL,
                         address character varying(255),
                         name character varying(255),
                         schemaname character varying(255),
                         uuid uuid,
                         schema_id bigint
);


ALTER TABLE account OWNER TO postgres;


ALTER TABLE account ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME account_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );



CREATE TABLE center_user (
                             id bigint NOT NULL,
                             username character varying(255)
);


ALTER TABLE center_user OWNER TO postgres;


CREATE TABLE code_label (
                            id bigint NOT NULL,
                            label character varying(255)
);


ALTER TABLE code_label OWNER TO postgres;


ALTER TABLE code_label ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME code_label_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );



CREATE TABLE condition (
                           id bigint NOT NULL,
                           rank integer NOT NULL
);


ALTER TABLE condition OWNER TO postgres;


ALTER TABLE condition ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME condition_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );




CREATE SEQUENCE hibernate_sequence
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE hibernate_sequence OWNER TO postgres;


CREATE TABLE patientinformation (
                                    id bigint NOT NULL,
                                    address character varying(255),
                                    birthday date,
                                    email character varying(255),
                                    firstname character varying(255),
                                    job character varying(255),
                                    lastname character varying(255),
                                    sex character varying(255),
                                    tel character varying(255)
);


ALTER TABLE patientinformation OWNER TO postgres;


ALTER TABLE patientinformation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME patientinformation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );



CREATE TABLE question (
                          id bigint NOT NULL,
                          label character varying(255),
                          rank integer NOT NULL,
                          type integer
);


ALTER TABLE question OWNER TO postgres;


CREATE TABLE question_answer (
                                 id bigint NOT NULL,
                                 questionid character varying(255),
                                 question_answer uuid
);


ALTER TABLE question_answer OWNER TO postgres;


ALTER TABLE question_answer ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME question_answer_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );



CREATE TABLE question_code_label (
                                     question_id bigint NOT NULL,
                                     content_id bigint NOT NULL
);


ALTER TABLE question_code_label OWNER TO postgres;


CREATE TABLE question_condition (
                                    question_id bigint NOT NULL,
                                    conditions_id bigint NOT NULL
);


ALTER TABLE question_condition OWNER TO postgres;


ALTER TABLE question ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME question_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );



CREATE TABLE questionanswer_content (
                                        questionanswer_id bigint NOT NULL,
                                        content character varying(255)
);


ALTER TABLE questionanswer_content OWNER TO postgres;


CREATE TABLE questionnaire_model (
                                     id bigint NOT NULL,
                                     name character varying(255)
);


ALTER TABLE questionnaire_model OWNER TO postgres;


ALTER TABLE questionnaire_model ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME questionnaire_model_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );



CREATE TABLE questionnaire_model_topic (
                                           questionnairemodel_id bigint NOT NULL,
                                           topics_id bigint NOT NULL
);


ALTER TABLE questionnaire_model_topic OWNER TO postgres;


CREATE TABLE questionnaire_request (
                                       id uuid NOT NULL,
                                       appointmentdate date,
                                       created_date timestamp without time zone,
                                       questionnairerequeststate character varying(255),
                                       used_for_qr_code boolean,
                                       questionnaire_model_id bigint
);


ALTER TABLE questionnaire_request OWNER TO postgres;


CREATE TABLE questionnaire_request_response (
                                                questionnaire_response_id uuid NOT NULL,
                                                questionnaire_request_id uuid NOT NULL
);


ALTER TABLE questionnaire_request_response OWNER TO postgres;


CREATE TABLE questionnaire_response (
                                        id uuid NOT NULL,
                                        filledby character varying(255),
                                        signature oid,
                                        signed_date timestamp without time zone,
                                        patient_information_id bigint
);


ALTER TABLE questionnaire_response OWNER TO postgres;


CREATE TABLE role (
                      id bigint NOT NULL,
                      name character varying(255)
);


ALTER TABLE role OWNER TO postgres;


ALTER TABLE role ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME role_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );



CREATE TABLE roles_permission (
                                  group_id bigint NOT NULL,
                                  role_id bigint NOT NULL
);


ALTER TABLE roles_permission OWNER TO postgres;


CREATE TABLE schema (
                        id bigint NOT NULL,
                        schema character varying(255)
);


ALTER TABLE schema OWNER TO postgres;


ALTER TABLE schema ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME schema_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );



CREATE TABLE topic (
                       id bigint NOT NULL,
                       name character varying(255)
);


ALTER TABLE topic OWNER TO postgres;


ALTER TABLE topic ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME topic_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );



CREATE TABLE topic_question (
                                topic_id bigint NOT NULL,
                                question_id bigint NOT NULL
);


ALTER TABLE topic_question OWNER TO postgres;


CREATE TABLE usergroup (
                           id bigint NOT NULL,
                           name character varying(255),
                           center_id bigint
);


ALTER TABLE usergroup OWNER TO postgres;


ALTER TABLE usergroup ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME usergroup_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );



CREATE TABLE users (
                       id bigint NOT NULL,
                       accountinitialized boolean NOT NULL,
                       email character varying(255),
                       emailchecked boolean NOT NULL,
                       enabled boolean NOT NULL,
                       firstname character varying(255),
                       lastname character varying(255),
                       password character varying(255),
                       username character varying(255),
                       uuid uuid,
                       role_id bigint
);


ALTER TABLE users OWNER TO postgres;


ALTER TABLE users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );



CREATE TABLE validation_token (
                                  id bigint NOT NULL,
                                  expirydate timestamp without time zone,
                                  token character varying(255),
                                  user_id bigint NOT NULL
);


ALTER TABLE validation_token OWNER TO postgres;


ALTER TABLE validation_token ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME validation_token_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


ALTER TABLE ONLY account
    ADD CONSTRAINT account_pkey PRIMARY KEY (id);



ALTER TABLE ONLY center_user
    ADD CONSTRAINT center_user_pkey PRIMARY KEY (id);



ALTER TABLE ONLY code_label
    ADD CONSTRAINT code_label_pkey PRIMARY KEY (id);



ALTER TABLE ONLY condition
    ADD CONSTRAINT condition_pkey PRIMARY KEY (id);




ALTER TABLE ONLY patientinformation
    ADD CONSTRAINT patientinformation_pkey PRIMARY KEY (id);



ALTER TABLE ONLY question_answer
    ADD CONSTRAINT question_answer_pkey PRIMARY KEY (id);



ALTER TABLE ONLY question
    ADD CONSTRAINT question_pkey PRIMARY KEY (id);



ALTER TABLE ONLY questionnaire_model
    ADD CONSTRAINT questionnaire_model_pkey PRIMARY KEY (id);



ALTER TABLE ONLY questionnaire_request
    ADD CONSTRAINT questionnaire_request_pkey PRIMARY KEY (id);



ALTER TABLE ONLY questionnaire_request_response
    ADD CONSTRAINT questionnaire_request_response_pkey PRIMARY KEY (questionnaire_response_id);



ALTER TABLE ONLY questionnaire_response
    ADD CONSTRAINT questionnaire_response_pkey PRIMARY KEY (id);



ALTER TABLE ONLY role
    ADD CONSTRAINT role_pkey PRIMARY KEY (id);



ALTER TABLE ONLY schema
    ADD CONSTRAINT schema_pkey PRIMARY KEY (id);



ALTER TABLE ONLY topic
    ADD CONSTRAINT topic_pkey PRIMARY KEY (id);



ALTER TABLE ONLY questionnaire_model_topic
    ADD CONSTRAINT uk_3hipdllaao38p3ydm04ykfile UNIQUE (topics_id);



ALTER TABLE ONLY question_condition
    ADD CONSTRAINT uk_c3j9afucyhwgqbiji7cejw419 UNIQUE (conditions_id);



ALTER TABLE ONLY question_code_label
    ADD CONSTRAINT uk_gfra459h10f68ix57sq63hcfx UNIQUE (content_id);



ALTER TABLE ONLY usergroup
    ADD CONSTRAINT usergroup_pkey PRIMARY KEY (id);



ALTER TABLE ONLY users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);



ALTER TABLE ONLY validation_token
    ADD CONSTRAINT validation_token_pkey PRIMARY KEY (id);





ALTER TABLE ONLY usergroup
    ADD CONSTRAINT fk21jf5qqtmi82079e3srv54ay5 FOREIGN KEY (center_id) REFERENCES account(id);



ALTER TABLE ONLY questionnaire_response
    ADD CONSTRAINT fk2egtlbowpcsohqh6yrljaj6uy FOREIGN KEY (patient_information_id) REFERENCES patientinformation(id);



ALTER TABLE ONLY question_condition
    ADD CONSTRAINT fk5ngso6p8stadg6blhv0af61pk FOREIGN KEY (conditions_id) REFERENCES condition(id);



ALTER TABLE ONLY questionnaire_model_topic
    ADD CONSTRAINT fk7hfh2ivaceroh4ekjhdsx9t8u FOREIGN KEY (questionnairemodel_id) REFERENCES questionnaire_model(id);



ALTER TABLE ONLY questionnaire_request_response
    ADD CONSTRAINT fk7wibwy04txgt94v0sskk3svod FOREIGN KEY (questionnaire_request_id) REFERENCES questionnaire_request(id);



ALTER TABLE ONLY account
    ADD CONSTRAINT fk9atym84mmjmr9fcutkkl5hvvi FOREIGN KEY (schema_id) REFERENCES schema(id);



ALTER TABLE ONLY topic_question
    ADD CONSTRAINT fkb1romdjtd8acx5q355fsphjq FOREIGN KEY (topic_id) REFERENCES topic(id);



ALTER TABLE ONLY questionanswer_content
    ADD CONSTRAINT fkcttym35qvao28hxdgxv9fhsro FOREIGN KEY (questionanswer_id) REFERENCES question_answer(id);



ALTER TABLE ONLY question_condition
    ADD CONSTRAINT fkcyiqexhy7b2g3lusdhpf2665q FOREIGN KEY (question_id) REFERENCES question(id);



ALTER TABLE ONLY questionnaire_model_topic
    ADD CONSTRAINT fkehadoxtxh6xlpd5n7qha9n19f FOREIGN KEY (topics_id) REFERENCES topic(id);



ALTER TABLE ONLY topic_question
    ADD CONSTRAINT fkhkohnm88p0bqlvbwxekk39jp6 FOREIGN KEY (question_id) REFERENCES question(id);



ALTER TABLE ONLY question_code_label
    ADD CONSTRAINT fkhu6gcfcksx8oggg2dats2x5tl FOREIGN KEY (content_id) REFERENCES code_label(id);



ALTER TABLE ONLY questionnaire_request
    ADD CONSTRAINT fkloed18y5fox9lf9l9ht0u0etw FOREIGN KEY (questionnaire_model_id) REFERENCES questionnaire_model(id);



ALTER TABLE ONLY questionnaire_request_response
    ADD CONSTRAINT fkoderxq0jpx84bacy7ycagod5s FOREIGN KEY (questionnaire_response_id) REFERENCES questionnaire_response(id);



ALTER TABLE ONLY roles_permission
    ADD CONSTRAINT fkodts4ho7oauica2x8edp397r5 FOREIGN KEY (group_id) REFERENCES usergroup(id);



ALTER TABLE ONLY users
    ADD CONSTRAINT fkp4cv14a2jly72ke5ra0csfcff FOREIGN KEY (role_id) REFERENCES usergroup(id);



ALTER TABLE ONLY question_answer
    ADD CONSTRAINT fkqmv6siytmnj0uah23t1xkrgpe FOREIGN KEY (question_answer) REFERENCES questionnaire_response(id);



ALTER TABLE ONLY validation_token
    ADD CONSTRAINT fkrh9uoclxjl8m4mn844gdtgnt4 FOREIGN KEY (user_id) REFERENCES users(id);



ALTER TABLE ONLY question_code_label
    ADD CONSTRAINT fkt6u43x1o5o175ktkg5ffbgmig FOREIGN KEY (question_id) REFERENCES question(id);



ALTER TABLE ONLY roles_permission
    ADD CONSTRAINT fktjf5ade20d1jhapaijxgwrvcv FOREIGN KEY (role_id) REFERENCES role(id);




